imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_product:
    resources:
        product:
            classes:
                controller: Nedac\SyliusOrderNowPlugin\Controller\ProductController
        product_association:
            classes:
                controller: Nedac\SyliusOrderNowPlugin\Controller\ProductAssociationController

sylius_review:
    resources:
        product:
            review:
                classes:
                    controller: Nedac\SyliusOrderNowPlugin\Controller\ProductReviewController
